### ISSUE TITLE
Missing Localization Key

### ISSUE THREAD

**Issue by tinygrox** [KentHaeger/SaveOurShip2-Old#1]
Hello, these texts seem to have forgotten to be localized:

https://github.com/KentHaeger/SaveOurShip2/blob/955788ff1c41d8d4a6c7c28c3c8122922618a1ab/Source/1.5/Comp/CompBuildingConsciousness.cs#L27

https://github.com/KentHaeger/SaveOurShip2/blob/955788ff1c41d8d4a6c7c28c3c8122922618a1ab/Source/1.5/Comp/CompBuildingConsciousness.cs#L471-L479

https://github.com/KentHaeger/SaveOurShip2/blob/955788ff1c41d8d4a6c7c28c3c8122922618a1ab/Source/1.5/Building/Building_ShipBridge.cs#L877-L878

https://github.com/KentHaeger/SaveOurShip2/blob/955788ff1c41d8d4a6c7c28c3c8122922618a1ab/Source/1.5/Building/Building_ShipBridge.cs#L892-L893

https://github.com/KentHaeger/SaveOurShip2/blob/955788ff1c41d8d4a6c7c28c3c8122922618a1ab/Source/1.5/Building/Building_ShipBridge.cs#L907-L908

https://github.com/KentHaeger/SaveOurShip2/blob/955788ff1c41d8d4a6c7c28c3c8122922618a1ab/Source/1.5/Building/Building_ShipBridge.cs#L922-L923

https://github.com/KentHaeger/SaveOurShip2/blob/955788ff1c41d8d4a6c7c28c3c8122922618a1ab/Source/1.5/Building/Building_ShipBridge.cs#L1197-L1206

https://github.com/KentHaeger/SaveOurShip2/blob/955788ff1c41d8d4a6c7c28c3c8122922618a1ab/Source/1.5/Comp/ShipMapComp.cs#L2360

plz 🥹

**Comment by KentHaeger** [comment]
Fixed in the latest, thanks!
