### ISSUE TITLE
Archotech Spore Will Never Unlock If Psychic Amplifier is translated

### ISSUE THREAD

**Issue by tinygrox** [KentHaeger/SaveOurShip2-Old#4]
if the player has translated the **Psychic Amplifier**(_1.5/Defs/Misc/ShipDefs/Mechanoid/MechPsychicAmp.xml_) to other language, then players will nerver unlock the **archotech spore**!

so maybe the problem is here:

https://github.com/KentHaeger/SaveOurShip2/blob/f31b91ed9568ebd1c5969406464012df79b84e20/Source/1.5/Building/Building_ShipBridge.cs#L1172-L1178

**Comment by KentHaeger** [comment]
Thanks for reporting this - issue has been fixed in the Testing branch and will soon be pushed to Steam.
